name: bus_seva
description: "A mobile app for real-time bus tracking and booking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  uuid: ^4.5.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  geolocator: ^14.0.2

flutter:
  uses-material-design: true

  # Add an assets section to include the entire fonts directory
  assets:
    - assets/fonts/

  # Keep your custom font declaration
  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Medium.otf
        - asset: assets/fonts/Cera-Pro-Bold.otf