// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA82OORs1OmOmhd4KKNGfDlkVRcew3v8u8',
    appId: '1:692459200509:web:39ab42d39efb25d05d0394',
    messagingSenderId: '692459200509',
    projectId: 'bus-seva-b152d',
    authDomain: 'bus-seva-b152d.firebaseapp.com',
    storageBucket: 'bus-seva-b152d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6eivZIKvVQWX5D7MATNmogqx_pfeKJ_o',
    appId: '1:692459200509:android:edbfbe6258589e8d5d0394',
    messagingSenderId: '692459200509',
    projectId: 'bus-seva-b152d',
    storageBucket: 'bus-seva-b152d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHtCNODAEHwkC8YY3Cb1wUFmR-PYWA3s',
    appId: '1:692459200509:ios:71be0eeb108cd1105d0394',
    messagingSenderId: '692459200509',
    projectId: 'bus-seva-b152d',
    storageBucket: 'bus-seva-b152d.firebasestorage.app',
    iosBundleId: 'com.example.busSeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHtCNODAEHwkC8YY3Cb1wUFmR-PYWA3s',
    appId: '1:692459200509:ios:71be0eeb108cd1105d0394',
    messagingSenderId: '692459200509',
    projectId: 'bus-seva-b152d',
    storageBucket: 'bus-seva-b152d.firebasestorage.app',
    iosBundleId: 'com.example.busSeva',
  );
}
